apiVersion : apps/v1
kind: Deployment
metadata:
  name: "axaksc1cluster-4361"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "axaksc1cluster-4361"
  template:
    metadata:
      labels:
        app: "axaksc1cluster-4361"
    spec:
      containers:
        - name: "axaksc1cluster-4361"
          image: "axionablesoftwarectimgsv1.azurecr.io/axaksc1cluster"
          ports:
          - containerPort: 80