apiVersion: v1
kind: Service
metadata:
    name: "axaksc1cluster-4361"
    labels:
        app: "axaksc1cluster-4361"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "axaksc1cluster-4361"