on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: axionablesoftwarectimgsv1.azurecr.io
        username: ${{ secrets.acr_axionablesoftwarectimgsv1_username }}
        password: ${{ secrets.acr_axionablesoftwarectimgsv1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/samples/aspnetmvcapp" -f  "samples/aspnetmvcapp/Dockerfile" -t axionablesoftwarectimgsv1.azurecr.io/axionkubeclust1:${{ github.sha }} --label dockerfile-path=samples/aspnetmvcapp/Dockerfile
        docker push axionablesoftwarectimgsv1.azurecr.io/axionkubeclust1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_axionkubeclust1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep axionkubeclust191f1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace axionkubeclust191f1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: axionkubeclust191f1
        container-registry-url: axionablesoftwarectimgsv1.azurecr.io
        container-registry-username: ${{ secrets.acr_axionablesoftwarectimgsv1_username }}
        container-registry-password: ${{ secrets.acr_axionablesoftwarectimgsv1_password }}
        secret-name: axionkubecludockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: axionkubeclust191f1
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          axionablesoftwarectimgsv1.azurecr.io/axionkubeclust1:${{ github.sha }}
        imagepullsecrets: |
          axionkubecludockerauth
